### ISSUE TITLE
Task Hafidz

### ISSUE THREAD

**Issue by fidzfadillah** [arrizal27/Jelita#1]
# Task List
_Terkait apa saja task yang akan dikerjakan. Sertakan screenshot jika memungkinkan._
- [x] Tambahkan asset ke project
- [x] Implementasi layout Home
- [x] Implementasi layout Riwayat Setor
- [x] Implementasi layout Tabung Minyak
- [x] Implementasi layout Setor Minyak
- [x] Assembling Frontend
- [x] Revisi
- [x] Add Intent

**Comment by fidzfadillah** [comment]
# Screenshot output
![Home jelita](https://user-images.githubusercontent.com/60495094/110951024-2630a080-8377-11eb-9b74-5cce78ca5c7e.jpg)
